apiVersion: apps/v1
kind: Deployment
metadata:
  name: poccharles-frontend
  namespace: poccharles
spec:
  selector:
    matchLabels:
      app: poccharles-frontend
  replicas: 1
  template:
    metadata:
      name: poccharles-frontend
      labels:
        app: poccharles-frontend
    spec:
      containers:
      - name: poccharles-frontend
        image: ailtonmsj/poccharles-frontend:v1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /www/
          name: index-base
#        - mountPath: /css/
#          name: index-style
#        - mountPath: /js/
#          name: index-script
#        command:
#        - sh
#        - -c
#        - chmod 777 /www/
#        - mkdir /www/css
#        - mkdir /www/js
#        - cp /css/* /www/css/ && cp /js/* /www/js/
      volumes:
      - name: index-base
        configMap:
          name: index-base
#      - name: index-style
#        configMap:
#          name: index-style
#      - name: index-script
#        configMap:
#          name: index-script
---
