apiVersion: v1
kind: Service
metadata:
  name: poccharles-frontend
  namespace: poccharles
spec:
  selector:
    app: poccharles-frontend
  ports:
    - name: http
      port: 8080
  type: NodePort
---